name: "Unit tests"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '7.2', '7.3', '7.4' ]
    steps:
      - uses: "actions/checkout@v3"

      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"

      - uses: "ramsey/composer-install@v2"

      - name: "Run unit tests"
        run: "./vendor/bin/phpunit -c phpunit.xml.dist --colors=always"
